<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mahdieh Tourani">
<meta name="dcterms.date" content="2026-09-29">

<title>WILD 541 – Research Design Lab – Research Design Lab</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-991b1886d3c685c7aa2b62b80640c7af.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Research Design Lab</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.qmd"> 
<span class="menu-text">Lessons</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Day05_2026-09-29_linear-models.html"><i class="bi bi-file-slides"></i>RevealJS (live)</a></li></ul></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">WILD 541 – Research Design Lab</h1>
<p class="subtitle lead">Lesson 5: Linear Models and Multiple Regression</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mahdieh Tourani </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="outline" class="level2">
<h2 class="anchored" data-anchor-id="outline">Outline</h2>
<ol type="1">
<li>Linear models</li>
<li>Simple linear regression</li>
<li>Multiple regression</li>
<li>Practice</li>
</ol>
</section>
<section id="linear-models" class="level1">
<h1>Linear models</h1>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<ul>
<li>We quantify linear relationships between a <strong>response variable</strong> (dependent) and <strong>explanatory variables</strong> (independent variables or predictors) using simple and multiple linear regression models.</li>
<li>Linear models (LMs) are relatively simple, but incredibly powerful</li>
</ul>
</section>
</section>
<section id="simple-linear-regression" class="level1">
<h1>Simple linear regression</h1>
<section id="simulate-data" class="level2">
<h2 class="anchored" data-anchor-id="simulate-data">Simulate data</h2>
<p>We will use (made-up) plant data to illustrate how simple linear regression models are fitted. First, we clear the workspace and simulate three datasets.</p>
<div class="cell">
<pre class="webr cell-code"><code>set.seed(541)
# data1: intercept-only (plant heights)
data1 &lt;- data.frame(id        = paste0("A", 1:100),
                    height_cm = rnorm(100, mean = 23.09, sd = 2.82))
# data2: height ~ nitrogen
data2 &lt;- data.frame(id             = paste0("A", 1:100),
                    nitrogen_gsqm  = runif(100, 50, 700),
                    height_cm      = NA)
data2$height_cm &lt;- 23.15 + 0.00985 * data2$nitrogen_gsqm + rnorm(100, 0, 2.84)
# data3: height ~ species (A vs B)
data3 &lt;- data.frame(id      = paste0("plant", 1:100),
                    species = rep(c("Species A", "Species B"), 50))
data3$height_cm &lt;- ifelse(data3$species == "Species A",
                          rnorm(50, 23.53, 2.8),
                          rnorm(50, 20.17, 2.8))</code></pre>
</div>
<blockquote class="blockquote">
<p>These data consist of the individual identification (id) and height (in cm) of 100 plants. All heights were measured 30 days after germination.</p>
</blockquote>
</section>
<section id="intercept-only-model" class="level2">
<h2 class="anchored" data-anchor-id="intercept-only-model">Intercept-only model</h2>
<p>The height of the plants is our variable of interest and we can fit a simple linear regression model using the lm() function. You can specify an intercept-only model by using a “1” after the tilde (∼) in the regression formula.</p>
<div class="cell">
<pre class="webr cell-code"><code>library(stats)
m1 &lt;- stats::lm(height_cm ~ 1, data = data1)
summary(m1)</code></pre>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We have a response variable (height_cm), but no predictor variables. Therefore, we cannot estimate a slope, only an intercept term. In the absence of a slope, the intercept is equivalent to the mean height of all plants.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The model output can be displayed with the summary() function.</p>
</div>
</div>
</section>
<section id="intercept-only-model-1" class="level2">
<h2 class="anchored" data-anchor-id="intercept-only-model-1">Intercept-only model</h2>
<p>The intercept value is the average height (in cm) of plants in this sample. The low p-value indicates that this value is significantly different from 0. Next, let’s plot the data and add the regression line.</p>
<div class="cell">
<pre class="webr cell-code"><code>plot(data1$height_cm,
     pch = 19, 
     col = "grey",
     ylab = "Plant height (cm)")
abline(m1, col = "red", lwd = 2)</code></pre>
</div>
</section>
<section id="intercept-only-model-2" class="level2">
<h2 class="anchored" data-anchor-id="intercept-only-model-2">Intercept-only model</h2>
<p>To better understand what residuals are, let’s add them to the plot as well. To do so, we obtain the model-predicted value for each data point (i.e., the height a plant would have had if it were on the regression line) using the predict() function. Then we just connect each data point with its predicted value using segments().</p>
<div class="cell">
<pre class="webr cell-code"><code>plot(data1$height_cm,
     pch = 19,
     col = "grey",
     ylab = "Plant height (cm)")
abline(m1, col = "red", lwd = 2)
fit &lt;- predict(m1)
segments(seq_along(data1$height_cm),
         fit,
         seq_along(data1$height_cm),
         data1$height_cm)</code></pre>
</div>
</section>
<section id="intercept-only-model-3" class="level2">
<h2 class="anchored" data-anchor-id="intercept-only-model-3">Intercept-only model</h2>
<p>Plotting a scatter plot or a regression line is not that useful when dealing with an intercept-only model. As an alternative, we can plot the density distribution of the data (the response variable) and then superimpose both the calculated and model-estimated mean. And as we just mentioned, these are identical.</p>
<div class="cell">
<pre class="webr cell-code"><code>plot(density(data1$height_cm))
abline(v = mean(data1$height_cm), lwd = 6, col = grey(0.4))  # calculated mean
abline(v = coef(m1), lwd = 2, col = "orange")   # model estimated mean</code></pre>
</div>
</section>
<section id="continuous-predictor" class="level2">
<h2 class="anchored" data-anchor-id="continuous-predictor">Continuous predictor</h2>
<p>Generally, in regression analysis, we are interested in quantifying the relationship between predictor and response variables. We now inspect data2, which, in addition to each plant’s height, also contains the amount of Nitrogen added to each plant’s growing soil (g per <span class="math inline">\(m^2\)</span>). First, we inspect the data and visualize plant height against nitrogen addition:</p>
<div class="cell">
<pre class="webr cell-code"><code>head(data2)
plot(height_cm ~ nitrogen_gsqm,
     data = data2,
     pch = 19,
     col = "grey",
     xlab = expression(Nitrogen~addition~(g/m^2)),
     ylab = "Plant height (cm)")</code></pre>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Always include units with axes labels.</p>
</div>
</div>
</section>
<section id="continuous-predictor-1" class="level2">
<h2 class="anchored" data-anchor-id="continuous-predictor-1">Continuous predictor</h2>
<p>We can fit a linear regression model to the data; this model includes a slope term for the effect of soil nitrogen concentration on plant height. The intercept term is implied and does not need to be specified in the formula.</p>
<div class="cell">
<pre class="webr cell-code"><code>m2 &lt;- stats::lm(height_cm ~ nitrogen_gsqm, data = data2)
summary(m2)</code></pre>
</div>
</section>
<section id="continuous-predictor-2" class="level2">
<h2 class="anchored" data-anchor-id="continuous-predictor-2">Continuous predictor</h2>
<p>The intercept (23.15 cm) is the expected height of a plant when the nitrogen added to the soil is 0 g /<span class="math inline">\(m^2\)</span>. The slope coefficient (0.0099 cm) is the expected increase in plant height in cm for every 1 g /<span class="math inline">\(m^2\)</span> increase in nitrogen added to the soil. The low p-value indicates that this slope is significantly different from 0.</p>
<blockquote class="blockquote">
<p>How would you summarize this finding?</p>
</blockquote>
<div class="incremental">
<p>One way to summarize this finding could be: We detected a significant positive relationship between plant height and the amount of nitrogen added to the soil (beta = 0.01, t = 8.11, p &lt;0.001). For example, a plant supplemented with 100 g soil nitrogen reached an average height of 24.14 cm compared with 23.15 cm for a plant without supplementary nitrogen.</p>
</div>
</section>
<section id="continuous-predictor-3" class="level2">
<h2 class="anchored" data-anchor-id="continuous-predictor-3">Continuous predictor</h2>
<p>We can use the model object to add the regression line to the scatter plot. And as earlier, we can also show the residuals in the same plot.</p>
<div class="cell">
<pre class="webr cell-code"><code>plot(height_cm ~ nitrogen_gsqm, 
     data = data2,
     pch = 19,
     col = "grey",
     xlab = "Nitrogen addition (g/m^2)",
     ylab = "Plant height (cm)")
abline(m2, col = "red", lwd = 2)
fit &lt;- predict(m2)
segments(data2$nitrogen_gsqm,
         fit,
         data2$nitrogen_gsqm,
         data2$height_cm)</code></pre>
</div>
</section>
<section id="categorical-predictor" class="level2">
<h2 class="anchored" data-anchor-id="categorical-predictor">Categorical predictor</h2>
<p>We can also use categorical predictor variables. In a linear regression, such variables are dealt with by turning them into so-called dummy variables. This is done by setting one level as a reference value (set to 0; this is the one associated with the intercept). All other levels (set to 1) are then compared with the reference level, one by one. We illustrate the use of categorical predictors in simple linear regression using a new version of the plant data.</p>
<div class="cell">
<pre class="webr cell-code"><code>head(data3)
</code></pre>
</div>
<blockquote class="blockquote">
<p>This data set contains the id and height for two species of plants (species A and B).</p>
</blockquote>
</section>
<section id="categorical-predictor-1" class="level2">
<h2 class="anchored" data-anchor-id="categorical-predictor-1">Categorical predictor</h2>
<p>Next, we fit the simple linear regression with species as the predictor variable:</p>
<div class="cell">
<pre class="webr cell-code"><code>m3 &lt;- stats::lm(height_cm ~ species, data = data3)
summary(m3)</code></pre>
</div>
</section>
<section id="categorical-predictor-2" class="level2">
<h2 class="anchored" data-anchor-id="categorical-predictor-2">Categorical predictor</h2>
<p>The intercept (23.53 cm) is the expected height of a plant of the reference species (A). The slope coefficient (-3.36 cm) is the expected difference in plant height of species B compared with species A. The negative coefficient indicates that the height of species B is (on average) lower than the height of species A. The low p-value indicates that the difference is significant. &gt;How would you summarize this finding?</p>
</section>
<section id="categorical-predictor-3" class="level2">
<h2 class="anchored" data-anchor-id="categorical-predictor-3">Categorical predictor</h2>
<p>One way to summarize this finding could be: Species A grew significantly higher than species B (beta = -3.36, t = -5.991, p &lt;0.001). The average height following a 30-day growing period for species A was 23.53 cm, compared with 20.17 cm for species B.</p>
</section>
<section id="categorical-predictor-4" class="level2">
<h2 class="anchored" data-anchor-id="categorical-predictor-4">Categorical predictor</h2>
<p>Finally, we plot the data and add the regression line:</p>
<div class="cell">
<pre class="webr cell-code"><code>boxplot(height_cm ~ species,
        data = data3,
        at = c(0, 1),
        xlab = "",
        ylab = "Plant height (cm)")
abline(m3, col = "red", lwd = 2)</code></pre>
</div>
</section>
<section id="your-turn" class="level2">
<h2 class="anchored" data-anchor-id="your-turn">Your turn</h2>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice 1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice 1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using your own data:</p>
<ol type="1">
<li>Identify variables in your data set that can be used as response and predictor variables in simple linear regression</li>
<li>Fit at least one LM with a <strong>continuous</strong> predictor and one with a <strong>categorical</strong> predictor.</li>
<li>Inspect the output and write a 1–3 sentence interpretation as a comment in your R script.</li>
<li>Generate figures showing the data and the regression line for each of the regression models you fit.</li>
</ol>
</div>
</div>
</section>
</section>
<section id="multiple-regression" class="level1">
<h1>Multiple regression</h1>
<section id="overview-1" class="level2">
<h2 class="anchored" data-anchor-id="overview-1">Overview</h2>
<p>Regression models can have multiple predictors. This lesson will give you a basic understanding of the effects estimates (coefficients) generated by multiple linear regression. When the effects of multiple predictor variables in a regression are independent of each other, we refer to them as additive effects. Today, we look at three examples with different predictor variables that have additive effects on the response.</p>
<div class="cell">
<pre class="webr cell-code"><code>p1 &lt;- data.frame(id        = paste0("P", 1:100),
                 species   = rep(c("Species A", "Species B"), 50),
                 pesticide = rep(c(FALSE, TRUE), each = 50),
                 height_cm = NA) # Plant Data 1: species + pesticide (categorical + categorical)
p1$height_cm &lt;- 23.5 +
                ifelse(p1$species == "Species B", -3.4, 0) +
                ifelse(p1$pesticide, 2.1, 0) +
                rnorm(100, 0, 2.5)
p2 &lt;- data.frame(nitrogen_gsqm = runif(100, 50, 700),
                 species       = rep(c("Species A", "Species B"), 50),
                 height_cm     = NA) # Plant Data 2: nitrogen + species (continuous + categorical)
p2$height_cm &lt;- 22 +
                0.01 * p2$nitrogen_gsqm +
                ifelse(p2$species == "Species B", -3.0, 0) +
                rnorm(100, 0, 2.5)
p3 &lt;- data.frame( nitrogen_gsqm = runif(100, 50, 700),
                  temperature   = rep(c(15, 25), 50),
                  height_cm     = NA) # Plant Data 3: nitrogen + temperature (continuous + continuous)
p3$height_cm &lt;- 20 +
                0.01 * p3$nitrogen_gsqm +
                0.5  * p3$temperature +
                rnorm(100, 0, 2.5)</code></pre>
</div>
</section>
<section id="categorical-categorical" class="level2">
<h2 class="anchored" data-anchor-id="categorical-categorical">Categorical + Categorical</h2>
<p>We fit a linear regression model to the first data object. This regression model contains the additive effects of species (Species A and Species B) and whether pesticide was applied during the growth period (TRUE/FALSE).</p>
<div class="cell">
<pre class="webr cell-code"><code>m1 &lt;- stats::lm(height_cm ~ species + pesticide, data = p1)
summary(m1)</code></pre>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The output contains separate coefficients for the intercept and every effect included in the model. Remember, categorical variables are treated as dummy variables, with one category serving as the intercept value (0) to which each additional category is then compared.</p>
</div>
</div>
</section>
<section id="categorical-categorical-1" class="level2">
<h2 class="anchored" data-anchor-id="categorical-categorical-1">Categorical + Categorical</h2>
<p>The model object essentially contains a machine that can be used to make predictions, i.e., to calculate the expected value of the response variable (height_cm) given certain values of the predictor variables (species and pesticide).</p>
<p>To make a prediction, we first create a new data object (in this case, one that contains all possible combinations of species and pesticide). We then provide that data object to the predict() function which generates the predictions (fitted values of plant height) for each set of predictor values, as well as the associated standard errors.</p>
<div class="cell">
<pre class="webr cell-code"><code>new_data &lt;- expand.grid(species   = c("Species A", "Species B"),
                        pesticide = c(FALSE, TRUE))
temp &lt;- predict(m1, newdata = new_data, se.fit = TRUE)
new_data$fit    &lt;- temp$fit
new_data$uci    &lt;- new_data$fit + 1.96 * temp$se.fit
new_data$lci    &lt;- new_data$fit - 1.96 * temp$se.fit
</code></pre>
</div>
</section>
<section id="categorical-categorical-2" class="level2">
<h2 class="anchored" data-anchor-id="categorical-categorical-2">Categorical + Categorical</h2>
<p>We can use what you have previously learned about plotting in R to generate a graph that visualizes the results (model predictions).</p>
<div class="cell">
<pre class="webr cell-code"><code>cols &lt;- c("orange", "turquoise")
names(cols) &lt;- sort(unique(new_data$species))

plot(fit ~ as.numeric(pesticide),
     data = new_data,
     xlim = c(-0.25, 1.25),
     col  = cols[species],
     pch = 19,
     cex = 2,
     ylim = c(min(new_data$lci), max(new_data$uci)),
     axes = FALSE,
     xlab = "Treatment",
     ylab = "Height (cm)")
axis(1, at = c(0, 1), labels = c("w/o pesticide", "w/ pesticide"))
axis(2)
# Add confidence intervals
segments(as.numeric(new_data$pesticide),
         new_data$lci,
         as.numeric(new_data$pesticide),
         new_data$uci,
         col  = cols[new_data$species],
         lwd  = 5,
         lend = 1)
# Add legend
legend("topleft", 
       legend = names(cols), 
       pch    = 19,
       pt.cex = 2,
       col    = cols, 
       bty    = "n")</code></pre>
</div>
</section>
<section id="continuous-categorical" class="level2">
<h2 class="anchored" data-anchor-id="continuous-categorical">Continuous + Categorical</h2>
<p>Let’s fit a model with one continuous and one categorical predictor variable.</p>
<div class="cell">
<pre class="webr cell-code"><code>m2 &lt;- stats::lm(height_cm ~ nitrogen_gsqm + species, data = p2)
summary(m2)</code></pre>
</div>
</section>
<section id="continuous-categorical-1" class="level2">
<h2 class="anchored" data-anchor-id="continuous-categorical-1">Continuous + Categorical</h2>
<p>Then create a new table with combination of predictor variables and use the predict ():</p>
<div class="cell">
<pre class="webr cell-code"><code>n_range  &lt;- seq(min(p2$nitrogen_gsqm),
                max(p2$nitrogen_gsqm),
                length.out = 50)
new_data &lt;- expand.grid(nitrogen_gsqm = n_range,
                        species       = c("Species A", "Species B"))
temp &lt;- predict(m2, newdata = new_data, se.fit = TRUE)
new_data$fit &lt;- temp$fit
new_data$uci &lt;- new_data$fit + 1.96 * temp$se.fit
new_data$lci &lt;- new_data$fit - 1.96 * temp$se.fit</code></pre>
</div>
</section>
<section id="continuous-categorical-2" class="level2">
<h2 class="anchored" data-anchor-id="continuous-categorical-2">Continuous + Categorical</h2>
<p>Finally, plot the results:</p>
<div class="cell">
<pre class="webr cell-code"><code>cols &lt;- c("orange", "turquoise")
names(cols) &lt;- sort(unique(new_data$species))

plot(height_cm ~ nitrogen_gsqm,
     data = p2,
     pch = 19,
     col = cols[species],
     cex = 0.4,
     ylab = "Height (cm)",
     xlab = "Nitrogen (g/m²)")
for (sp in names(cols)) {
  sub &lt;- new_data[new_data$species == sp, ]
  # Add regression line
  lines(fit ~ nitrogen_gsqm, data = sub, col = cols[sp], lwd = 3)
  # Add confidence intervals
  lines(lci ~ nitrogen_gsqm, data = sub, col = cols[sp], lty = 2)
  lines(uci ~ nitrogen_gsqm, data = sub, col = cols[sp], lty = 2)
}
# Add legend
legend("topleft", 
       legend = names(cols),
       lwd    = 3, 
       col    = cols,
       bty    = "n", 
       title  = "Species")</code></pre>
</div>
</section>
<section id="continuous-continuous" class="level2">
<h2 class="anchored" data-anchor-id="continuous-continuous">Continuous + Continuous</h2>
<p>Let’s fit a model with two continuous predictor variables.</p>
<div class="cell">
<pre class="webr cell-code"><code>m3 &lt;- stats::lm(height_cm ~ nitrogen_gsqm + temperature, data = p3)
summary(m3)</code></pre>
</div>
</section>
<section id="continuous-continuous-1" class="level2">
<h2 class="anchored" data-anchor-id="continuous-continuous-1">Continuous + Continuous</h2>
<p>We can make predictions and visualize the results as before.</p>
<div class="cell">
<pre class="webr cell-code"><code>n_range  &lt;- seq(min(p3$nitrogen_gsqm),
                max(p3$nitrogen_gsqm),
                length.out = 50)
new_data &lt;- expand.grid(nitrogen_gsqm = n_range,
                        temperature   = c(15, 25))
temp &lt;- predict(m3, newdata = new_data, se.fit = TRUE)
new_data$fit &lt;- temp$fit
new_data$uci &lt;- new_data$fit + 1.96 * temp$se.fit
new_data$lci &lt;- new_data$fit - 1.96 * temp$se.fit

cols  &lt;- c("orange", "turquoise")
cats  &lt;- sort(unique(new_data$temperature))
names(cols) &lt;- as.character(cats)
plot(height_cm ~ nitrogen_gsqm,
     data = p3,
     pch = 19,
     cex = 0.4,
     ylab = "Height (cm)", xlab = "Nitrogen (g/m²)")

for (t in as.character(cats)) {
  sub &lt;- new_data[as.character(new_data$temperature) == t, ]
  #Add regression line
  lines(fit ~ nitrogen_gsqm, data = sub, col = cols[t], lwd = 3)
  #Add confidence intervals
  lines(lci ~ nitrogen_gsqm, data = sub, col = cols[t], lty = 2)
  lines(uci ~ nitrogen_gsqm, data = sub, col = cols[t], lty = 2)
}
#Add legend
legend("topleft",
       legend = paste(cats, "°C"),
       lwd = 3, 
       col = cols,
       bty = "n",
       title = "Temperature")</code></pre>
</div>
</section>
<section id="your-turn-1" class="level2">
<h2 class="anchored" data-anchor-id="your-turn-1">Your turn</h2>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice 2">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice 2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using your own data:</p>
<ol type="1">
<li>Fit at least one multiple regression with additive terms of two predictor variables.</li>
<li>Inspect the output and write a 1–3 sentence interpretation as a comment in your R script.</li>
<li>Generate figures showing the data and the regression line for each of the regression models you fit.</li>
</ol>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>